name: 'Update Android Manifest package meta-data action'
description: 'Update the metadata in a AndroidManifest.xml file'
author: 'jacinlowe'
inputs:
  android-manifest-path:
    description: 'Relative path for the AndroidManifest.xml file.'
    required: true
  metadata-key:
    description: 'meta-data android:name key you are looking to update'
    required: true
  metadata-value:
    description: 'android:value the value you want to insert'
    required: true
  print-file:
    description: 'Output the AndroidManifest.xml file in console'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'green'
