name: sample

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  demo:
    runs-on: ubuntu-latest
    name: Update AndroidManifest.xml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update AndroidManifest
        uses: ./
        with:
          android-manifest-path: './samples/AndroidManifest.xml'
          metadata-key: 'com.google.android.geo.API_KEY'
          metadata-value: 'XVDJERjerjijeriJIRE551558ER'
          print-file: true
