name: versions

on:
  # pull_request:
  #   paths-ignore:
  #     - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  local-version:
    runs-on: ubuntu-latest
    name: Update AndroidManifest.xml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update AndroidManifest
        uses: ./
        with:
          android-manifest-path: './samples/AndroidManifest.xml'
          metadata-key: 'com.google.android.geo.API_KEY'
          metadata-value: 'XVDJERjerjijeriJIRE551558ER'
          print-file: true

      - name: Update AndroidManifest-1
        uses: ./
        with:
          android-manifest-path: './samples/AndroidManifest-1.xml'
          metadata-key: 'com.google.android.geo.API_KEY'
          metadata-value: 'XVDJERjerjijeriJIRE551558ER'
          print-file: true
          
      - name: Update AndroidManifest-3 with metadata
        uses: ./
        with:
          android-manifest-path: './samples/AndroidManifest-3.xml'
          metadata-key: 'com.google.android.geo.API_KEY'
          metadata-value: 'XVDJERjerjijeriJIRE551558ER'
      
      # Test should fail
      # - name: Update AndroidManifest-2 without metadata
      #   uses: ./
      #   with:
      #     android-manifest-path: './samples/AndroidManifest-2.xml'
      #     metadata-key: 'com.google.android.geo.API_KEY'
      #     metadata-value: 'XVDJERjerjijeriJIRE551558ER'
